<?php

declare(strict_types=1);

namespace App\Http\Controllers\Dashboard\Finance;

use App\Enums\FinanceExpenseStatus;
use App\Http\Controllers\Controller;
use App\Http\Requests\Finance\FinanceExpenseRequest;
use App\Models\FinanceExpense;
use App\Models\FinanceExpenseCategory;
use App\Models\FinanceVendor;
use App\Services\Finance\FinanceExpenseCategoryService;
use App\Services\Finance\FinanceExpenseService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

class FinanceExpenseController extends Controller
{
    public function index(Request $request, FinanceExpenseService $service): Response
    {
        $this->authorize('viewAny', FinanceExpense::class);

        $filters = $request->only(['from', 'to', 'category_id', 'vendor_id', 'status', 'payment_method', 'store_id']);

        $expenses = $service->filteredQuery($filters)->paginate(20)->withQueryString();

        return Inertia::render('Dashboard/Finance/Expenses/Index', [
            'expenses' => $expenses,
            'filters' => $filters,
            'options' => $this->formOptions($request),
        ]);
    }

    public function create(Request $request): Response
    {
        $this->authorize('create', FinanceExpense::class);

        return Inertia::render('Dashboard/Finance/Expenses/Create', [
            'options' => $this->formOptions($request),
        ]);
    }

    public function store(FinanceExpenseRequest $request, FinanceExpenseService $service): RedirectResponse
    {
        $store = $request->user()->getActiveStore();
        abort_if($store?->organization === null, 422, 'No active organization.');

        $service->create($store->organization, $request->user(), $request->validated());

        return redirect()->route('dashboard.finance.expenses.index')->with('success', 'Expense recorded.');
    }

    public function edit(Request $request, FinanceExpense $expense): Response
    {
        $this->authorize('update', $expense);

        return Inertia::render('Dashboard/Finance/Expenses/Edit', [
            'expense' => $expense->load(['category:id,name', 'vendor:id,name', 'store:id,name']),
            'options' => $this->formOptions($request),
        ]);
    }

    public function update(FinanceExpenseRequest $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $service->update($expense, $request->validated());

        return redirect()->route('dashboard.finance.expenses.index')->with('success', 'Expense updated.');
    }

    public function destroy(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('delete', $expense);

        $wasPaid = $expense->status === FinanceExpenseStatus::Paid;
        $deleted = $service->delete($expense);

        $message = match (true) {
            $deleted => 'Expense deleted.',
            $wasPaid => 'This expense was already paid — cancelled instead of deleted, and a reversal was recorded.',
            default => 'Expense was generated by a recurring charge — cancelled instead of deleted.',
        };

        return back()->with('success', $message);
    }

    public function markPaid(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('update', $expense);

        $validated = $request->validate([
            'payment_method' => ['nullable', 'string'],
        ]);

        $service->markPaid($expense, $validated['payment_method'] ?? null);

        return back()->with('success', 'Expense marked as paid.');
    }

    public function markUnpaid(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('markUnpaid', $expense);

        $service->markUnpaid($expense);

        return back()->with('success', 'Expense marked as unpaid.');
    }

    public function cancel(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('update', $expense);

        $service->cancel($expense);

        return back()->with('success', 'Expense cancelled.');
    }

    private function formOptions(Request $request): array
    {
        $organization = $request->user()->getActiveStore()?->organization;
        if ($organization !== null) {
            app(FinanceExpenseCategoryService::class)->ensureSeeded($organization);
        }

        return [
            'categories' => FinanceExpenseCategory::query()->where('is_active', true)->orderBy('name')->get(['id', 'name']),
            'vendors' => FinanceVendor::query()->where('is_active', true)->orderBy('name')->get(['id', 'name']),
            'stores' => $organization?->stores()->orderBy('name')->get(['id', 'name']) ?? collect(),
        ];
    }
}
