<?php

declare(strict_types=1);

namespace App\Http\Controllers\Dashboard\Finance;

use App\Enums\FinanceDocumentType;
use App\Enums\FinanceExpenseJustificationType;
use App\Enums\FinanceExpenseStatus;
use App\Http\Controllers\Controller;
use App\Http\Requests\Finance\FinanceExpenseRequest;
use App\Models\FinanceExpense;
use App\Models\FinanceExpenseCategory;
use App\Models\FinanceVendor;
use App\Services\Finance\FinanceDocumentService;
use App\Services\Finance\FinanceExpenseCategoryService;
use App\Services\Finance\FinanceExpenseService;
use App\Services\Pos\DocumentGenerationService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response as HttpResponse;
use Inertia\Inertia;
use Inertia\Response;

class FinanceExpenseController extends Controller
{
    public function index(Request $request, FinanceExpenseService $service): Response
    {
        $this->authorize('viewAny', FinanceExpense::class);

        $filters = $request->only(['from', 'to', 'category_id', 'vendor_id', 'status', 'payment_method', 'store_id', 'justification_status', 'owner_review_status']);

        $expenses = $service->filteredQuery($filters)->paginate(20)->withQueryString();

        return Inertia::render('Dashboard/Finance/Expenses/Index', [
            'expenses' => $expenses,
            'filters' => $filters,
            'options' => $this->formOptions($request),
            'can' => [
                'review' => $request->user()->hasStorePermission($request->user()->getActiveStore(), 'finance.review_expenses'),
            ],
        ]);
    }

    public function create(Request $request): Response
    {
        $this->authorize('create', FinanceExpense::class);

        return Inertia::render('Dashboard/Finance/Expenses/Create', [
            'options' => $this->formOptions($request),
        ]);
    }

    public function store(FinanceExpenseRequest $request, FinanceExpenseService $service, FinanceDocumentService $documents): RedirectResponse
    {
        $store = $request->user()->getActiveStore();
        abort_if($store?->organization === null, 422, 'No active organization.');

        $expense = $service->create($store->organization, $request->user(), $request->validated());

        // Optional "Documents justificatifs" section on the Create page —
        // purely evidentiary, attached after the expense already exists;
        // never affects the expense itself or the ledger.
        if ($request->hasFile('documents')) {
            $documents->storeMany(
                documentable: $expense,
                organization: $store->organization,
                files: $request->file('documents'),
                uploadedBy: $request->user(),
                documentType: $request->validated('document_type'),
                description: $request->validated('document_description'),
                storeId: $expense->store_id,
            );

            // A document attached in this SAME request (e.g. the official
            // invoice uploaded right alongside "Yes, I have one") must be
            // reflected immediately — create() alone can't see it yet, it
            // ran before storeMany() above.
            $service->syncJustificationStatus($expense);
        }

        return redirect()->route('dashboard.finance.expenses.index')->with('success', 'Expense recorded.');
    }

    public function edit(Request $request, FinanceExpense $expense): Response
    {
        $this->authorize('update', $expense);

        return Inertia::render('Dashboard/Finance/Expenses/Edit', [
            'expense' => $expense->load([
                'category:id,name', 'vendor:id,name', 'store:id,name',
                'documents.uploadedBy:id,name',
                'ownerReviewedBy:id,name',
            ]),
            'options' => $this->formOptions($request),
            'can' => [
                'review' => $request->user()->can('review', $expense),
            ],
        ]);
    }

    public function update(FinanceExpenseRequest $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $service->update($expense, $request->validated());

        return redirect()->route('dashboard.finance.expenses.index')->with('success', 'Expense updated.');
    }

    public function destroy(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('delete', $expense);

        $wasPaid = $expense->status === FinanceExpenseStatus::Paid;
        $deleted = $service->delete($expense);

        $message = match (true) {
            $deleted => 'Expense deleted.',
            $wasPaid => 'This expense was already paid — cancelled instead of deleted, and a reversal was recorded.',
            default => 'Expense was generated by a recurring charge — cancelled instead of deleted.',
        };

        return back()->with('success', $message);
    }

    public function markPaid(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('update', $expense);

        $validated = $request->validate([
            'payment_method' => ['nullable', 'string'],
        ]);

        $service->markPaid($expense, $validated['payment_method'] ?? null);

        return back()->with('success', 'Expense marked as paid.');
    }

    public function markUnpaid(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('markUnpaid', $expense);

        $service->markUnpaid($expense);

        return back()->with('success', 'Expense marked as unpaid.');
    }

    public function cancel(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('update', $expense);

        $service->cancel($expense);

        return back()->with('success', 'Expense cancelled.');
    }

    /** Owner/admin review of an internal cash voucher / no-invoice expense — see FinanceExpensePolicy::review(). */
    public function approveJustification(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('review', $expense);

        $validated = $request->validate(['note' => ['nullable', 'string', 'max:2000']]);
        $service->approveJustification($expense, $request->user(), $validated['note'] ?? null);

        return back()->with('success', 'Expense approved internally.');
    }

    public function rejectJustification(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('review', $expense);

        $validated = $request->validate(['note' => ['nullable', 'string', 'max:2000']]);
        $service->rejectJustification($expense, $request->user(), $validated['note'] ?? null);

        return back()->with('success', 'Expense rejected — any recorded payment was reversed, not deleted.');
    }

    public function requestMoreInfo(Request $request, FinanceExpense $expense, FinanceExpenseService $service): RedirectResponse
    {
        $this->authorize('review', $expense);

        $validated = $request->validate(['note' => ['nullable', 'string', 'max:2000']]);
        $service->requestMoreInfo($expense, $request->user(), $validated['note'] ?? null);

        return back()->with('success', 'More information requested.');
    }

    /**
     * Stream a printable internal cash voucher for this expense — the
     * internal justification an accountant/owner signs and re-attaches as a
     * `internal_voucher` document (never itself a FinanceDocument or a
     * finance_transaction). Gated on `view` (read-only), not
     * finance.manage_expenses — printing is a paper-trail aid anyone who can
     * see the expense should be able to do. Route-model binding already
     * 404s a cross-organization expense before the policy is even reached.
     */
    public function voucher(Request $request, FinanceExpense $expense, DocumentGenerationService $documents): HttpResponse
    {
        $this->authorize('view', $expense);

        $pdf = $documents->renderInternalVoucherPdf($expense);

        return response($pdf, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => "inline; filename=\"internal-voucher-{$expense->id}.pdf\"",
        ]);
    }

    private function formOptions(Request $request): array
    {
        $organization = $request->user()->getActiveStore()?->organization;
        if ($organization !== null) {
            app(FinanceExpenseCategoryService::class)->ensureSeeded($organization);
        }

        return [
            'categories' => FinanceExpenseCategory::query()->where('is_active', true)->orderBy('name')->get(['id', 'name']),
            'vendors' => FinanceVendor::query()->where('is_active', true)->orderBy('name')->get(['id', 'name']),
            'stores' => $organization?->stores()->orderBy('name')->get(['id', 'name']) ?? collect(),
            'documentTypes' => collect(FinanceDocumentType::cases())->map(fn (FinanceDocumentType $t) => ['value' => $t->value, 'label' => $t->label()])->values(),
            'justificationTypes' => collect(FinanceExpenseJustificationType::cases())->map(fn (FinanceExpenseJustificationType $t) => ['value' => $t->value, 'label' => $t->label()])->values(),
        ];
    }
}
