<?php

declare(strict_types=1);

namespace App\Enums;

/** Lifecycle of one `fulfillment_documents` row — did we actually get bytes on disk? */
enum FulfillmentDocumentStatus: string
{
    /** Provider PDF bytes fetched server-side and written to the private disk. */
    case Stored = 'stored';
    /** SaaS-generated bytes (fallback label, pick ticket, manifest) written to the private disk. */
    case Generated = 'generated';
    /** The provider returned a URL, but fetching it server-side landed on an HTML page — it needs a provider dashboard session. */
    case ExternalUrlUnavailable = 'external_url_unavailable';
    /** The fetch attempt errored or returned something that is not a PDF. */
    case FetchFailed = 'fetch_failed';

    public function label(): string
    {
        return match ($this) {
            self::Stored => 'Stored',
            self::Generated => 'Generated',
            self::ExternalUrlUnavailable => 'Provider URL needs login',
            self::FetchFailed => 'Fetch failed',
        };
    }

    /** Whether there is a file on disk this row can hand back through the download route. */
    public function isDownloadable(): bool
    {
        return $this === self::Stored || $this === self::Generated;
    }
}
