<?php

declare(strict_types=1);

namespace App\Enums;

/** Kind of fulfilment paperwork stored in `fulfillment_documents`. */
enum FulfillmentDocumentType: string
{
    /** Per-parcel carrier label / ticket PDF (Ozon `pdf-delivery-note-tickets`). */
    case CarrierLabel = 'carrier_label';
    /** The provider's own Bon de Livraison sheet (Ozon `pdf-delivery-note`) — also the ramassage/handover note. */
    case DeliveryNote = 'delivery_note';
    /** A SaaS-generated pickup / ramassage manifest (for providers with no PDF of their own). */
    case PickupManifest = 'pickup_manifest';
    /** Internal pick/pack ticket generated by the SaaS (later phase). */
    case PickTicket = 'pick_ticket';
    /** SaaS-generated stand-in carrier label — used only when the official provider PDF cannot be fetched. */
    case FallbackLabel = 'fallback_label';

    public function label(): string
    {
        return match ($this) {
            self::CarrierLabel => 'Carrier label',
            self::DeliveryNote => 'Delivery note (BL)',
            self::PickupManifest => 'Pickup manifest',
            self::PickTicket => 'Pick ticket',
            self::FallbackLabel => 'Fallback label',
        };
    }

    /**
     * SaaS-generated / internal documents a store may later customise via a
     * DocumentTemplate. Provider PDFs (carrier_label, delivery_note) are
     * NEVER in this set — they are whatever Ozon/Sendit returns.
     *
     * @return array<int, self>
     */
    public static function customizable(): array
    {
        return [self::PickTicket, self::FallbackLabel, self::PickupManifest];
    }

    /** @return array<int, string> */
    public static function customizableValues(): array
    {
        return array_map(static fn (self $c) => $c->value, self::customizable());
    }

    public function isCustomizable(): bool
    {
        return in_array($this, self::customizable(), true);
    }
}
