<?php

declare(strict_types=1);

namespace App\Enums;

/** Kind of fulfilment paperwork stored in `fulfillment_documents`. */
enum FulfillmentDocumentType: string
{
    /** Per-parcel carrier label / ticket PDF (Ozon `pdf-delivery-note-tickets`). */
    case CarrierLabel = 'carrier_label';
    /** The provider's own Bon de Livraison sheet (Ozon `pdf-delivery-note`) — also the ramassage/handover note. */
    case DeliveryNote = 'delivery_note';
    /** A SaaS-generated pickup / ramassage manifest (for providers with no PDF of their own). */
    case PickupManifest = 'pickup_manifest';
    /** Internal pick/pack ticket generated by the SaaS (later phase). */
    case PickTicket = 'pick_ticket';
    /** SaaS-generated stand-in carrier label — used only when the official provider PDF cannot be fetched. */
    case FallbackLabel = 'fallback_label';

    public function label(): string
    {
        return match ($this) {
            self::CarrierLabel => 'Carrier label',
            self::DeliveryNote => 'Delivery note (BL)',
            self::PickupManifest => 'Pickup manifest',
            self::PickTicket => 'Pick ticket',
            self::FallbackLabel => 'Fallback label',
        };
    }
}
